[project]
name = "PySide Widgets Project"

[tool.pyside6-project]
files = ["add_astronaut.ui", "add_astronaut_dialog.py", "calc_window.ui", "calcwindow.py", "config.py", "database.py", "edit_astronaut_dialog.py", "edit_astronaut_dialog.ui", "main_window.ui", "mainwindow.py", "report_generator.py", "utils.py"]
